[tool.poetry]
name = "beachPatrol"
version = "0.1.0"
description = "A discord bot that patrols the beach."
authors = ["Drew&Pate <drew@lido.fi>"]
readme = "README.md"
packages = [
  { include = "commands",       from = "src" },
  { include = "extractors",     from = "src" },
  { include = "core",           from = "src" },
  { include = "tasks",          from = "src" },
  { include = "interface",      from = "src" },
  { include = "config.py",      from = "src" }
]


[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.82.0"
langchain = "^0.3.25"
langchain-community = "^0.3.24"
langchain-openai = "^0.3.18"
python-dotenv = "^1.1.0"
celery = "^5.5.2"
redis = "^6.1.0"
beautifulsoup4 = "^4.13.4"
yt-dlp = "^2025.5.22"
newspaper4k = "^0.9.3.1"
pymupdf = "^1.26.0"
python-telegram-bot = {extras = ["job-queue"], version = "^22.1"}
notion-client = "^2.3.0"
tweety-ns = "^2.3"
discord-py = "^2.5.2"
lxml-html-clean = "^0.4.2"
prometheus-client = "^0.22.0"


[tool.poetry.group.dev.dependencies]
deptry = "^0.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
