from config import OPENAI_MODEL
import re

MEDIA_CONFIGS = {
    "governance_forum": {
        "base_title": f"Ecosystem and Governance Updates",
        "disclaimers": (
            f"\n\n*(This summary was generated by a refined model. The following pages "
            f"contain a more comprehensive summary using: **{OPENAI_MODEL}**.)*\n\n"
        )
    },
    "article": {
        "base_title": f"Article Summary, model={OPENAI_MODEL}",
        "disclaimers": (
            "\n\n*(Above is the Executive Summary. Next pages contain a more "
            f"comprehensive summary.)*\n\n"
        )
    },
    "youtube": {
        "base_title": f"YouTube Video Summary, model={OPENAI_MODEL}",
        "disclaimers": (
            "\n\n*(Above is the Executive Summary. Next pages contain a more "
            f"comprehensive summary.)*\n\n"
        )
    },
    "twitter_space": {
        "base_title": f"Twitter Space Summary, model={OPENAI_MODEL}",
        "disclaimers": (
            "\n\n*(Above is the Executive Summary. Next pages contain a more "
            f"comprehensive summary.)*\n\n"
        )
    },
    "twitter_digest": {
        "base_title": f"Twitter Digest, model={OPENAI_MODEL}",
        "disclaimers": (
            "\n\n*(Above is the Executive Summary. Next pages contain a more "
            f"comprehensive summary.)*\n\n"
        )
    },
    "single_twitter_account": {
        "base_title": f"Single Twitter Account Summary, model={OPENAI_MODEL}",
        "disclaimers": (
            "\n\n*(Above is the Executive Summary. Next pages contain a more "
            "comprehensive summary of tweets for this user.)*\n\n"
        )
    },
    "tweet_summary": {
        "base_title": f"Tweet Summary, model={OPENAI_MODEL}",
        "disclaimers": (
            "\n\n*(Above is the Executive Summary. Next pages contain a more "
            "comprehensive summary of tweets for this user.)*\n\n"
        )
    },
}

DEFAULT_MEDIA_CONFIG = {
    "base_title": f"Update, model={OPENAI_MODEL}",
    "disclaimers": ""
}

def get_telegram_media_config(media_type: str) -> dict:
    """
    Returns a version of the media configuration for Telegram.
    It converts the disclaimer from its Markdown form to HTML by:
      - Stripping leading/trailing whitespace.
      - Removing the outer "*(" and ")*" markers if present.
      - Converting **text** to <b>text</b>.
      - Wrapping the entire disclaimer in <i>...</i>.
    This does not alter the original MEDIA_CONFIGS used by Discord.
    """
  
    config = MEDIA_CONFIGS.get(media_type, DEFAULT_MEDIA_CONFIG)
    new_config = config.copy()
    disclaimer = new_config.get("disclaimers", "")
    disclaimer = disclaimer.strip()
    if disclaimer.startswith("*(") and disclaimer.endswith(")*"):
        disclaimer = disclaimer[2:-2]
    # Replace **text** with <b>text</b>
    disclaimer = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", disclaimer)
    # Wrap the entire disclaimer in <i> tags
    disclaimer = f"<i>{disclaimer}</i>"
    new_config["disclaimers"] = disclaimer
    return new_config


def get_media_type_from_command(command_type: str) -> str:
    """
    Maps the given command type (case-insensitive) to the appropriate beautified media type.
    For example, "twitter_space" becomes "Twitter Space".
    If no match is found, returns "Update".
    """
    ct = command_type.lower()
    if ct == "governance_forum":
        return "Governance Digest"
    if ct == "article":
        return "Article"
    if ct == "youtube":
        return "YouTube"
    if ct == "twitter_space":
        return "Twitter Space"
    if ct == "twitter_digest":
        return "Twitter Digest"
    if ct in ("single_twitter_account", "twitter_account"):
        return "Twitter Account Digest"
    if ct == "tweet_summary":
        return "Tweet"
    return "Update"


def get_telegram_media_slug(command_type: str) -> str:
    """
    Maps the given command type (case-insensitive) to the corresponding slug
    used as key in the MEDIA_CONFIGS dictionary (for Telegram output).
    For example, "tweet_summary" will map to "tweet_summary" (all lowercase).
    """
    ct = command_type.lower()
    if ct == "governance_forum":
        return "governance_forum"
    if ct == "article":
        return "article"
    if ct == "youtube":
        return "youtube"
    if ct == "twitter_space":
        return "twitter_space"
    if ct == "twitter_digest":
        return "twitter_digest"
    if ct in ("single_twitter_account", "twitter_account"):
        return "single_twitter_account"
    if ct == "tweet_summary":
        return "tweet_summary"
    return "update"
